### ISSUE TITLE
Naming conventions

### ISSUE THREAD

**Issue by kkoomen** [rhysd/conflict-marker.vim#14]
I suggest you use `ours` and `theirs` in the README as this is more clear and reflects the actual git naming convention. Right now it's `ourselves` and `theirselves` which just sounds weird.

**Comment by rhysd** [comment]
Thanks for the point. Fixed in 30f281b.

**Comment by ranelpadon** [comment]
"@rhysd @kkoomen The `ours` and `theirs` are not always accurate/appropriate though: if I try to merge my branch to a release branch or master/main as target, the **HEAD** becomes `ours`, and my branch become `theirs` which is confusing. I expect that my branch should be `ours` regardless of the target. But it seems that `ours` always map to **HEAD**, am I correct?

VS Code has this naming: `Current Change` and `Upcoming Change`:
<img width="449" alt="Screen Shot 2021-04-15 at 2 33 42 PM" src="https://user-images.githubusercontent.com/4292088/114825244-8abca080-9df8-11eb-8bd0-b4ecce878892.png">

Atom has this naming though: `Our Changes` and `Their Changes`
<img width="675" alt="Screen Shot 2021-04-15 at 2 37 37 PM" src="https://user-images.githubusercontent.com/4292088/114825080-5517b780-9df8-11eb-968f-a3dab2db8f4a.png">

VS Code has better naming I think, since **HEAD** is not always `ours`, since it depends on the direction of the merge. Maybe we could tweak the behavior of the plugin to switch the "ours" as needed, or just use better naming like in VS Code? At the very least, I could customize my mapping instead of using the default `co` and `ct`. :)
